const ROUTES = [
    { id: '1', type: 'Short Haul', departure: 'IRFD', arrival: 'IPPH', routing: 'IRFD RDV/DCT/Active SID TOBAK KEMAD RDV/DCT/Active STAR IPPH' },
    { id: '2', type: 'Short Haul', departure: 'IPPH', arrival: 'IRFD', routing: 'IPPH RDV/DCT/Active SID KEMAD TOBAK RDV/DCT/Active STAR IRFD' },
    { id: '3', type: 'Short Haul', departure: 'IRFD', arrival: 'IMLR', routing: 'IRFD RDV/DCT/Active SID ROBUX MUONE RDV/DCT/Active STAR IMLR' },
    { id: '4', type: 'Short Haul', departure: 'IMLR', arrival: 'IRFD', routing: 'IMLR RDV/DCT/Active SID MUONE ROBUX RDV/DCT/Active STAR IRFD' },
    { id: '5', type: 'Short Haul', departure: 'IPPH', arrival: 'IMLR', routing: 'IPPH RDV/DCT/Active SID TINDR ONDER RDV/DCT/Active STAR IMLR' },
    { id: '6', type: 'Short Haul', departure: 'IMLR', arrival: 'IPPH', routing: 'IMLR RDV/DCT/Active SID ONDER TINDR RDV/DCT/Active STAR IPPH' },
    { id: '7', type: 'Short Haul', departure: 'IRFD', arrival: 'ISAU', routing: 'IRFD RDV/DCT/Active SID STACK HOGGS RDV/DCT/Active STAR ISAU' },
    { id: '8', type: 'Short Haul', departure: 'ISAU', arrival: 'IRFD', routing: 'ISAU RDV/DCT/Active SID HOGGS STACK RDV/DCT/Active STAR IRFD' },
    { id: '9', type: 'Short Haul', departure: 'IPPH', arrival: 'IZOL', routing: 'IPPH RDV/DCT/Active SID DOGGO MORRD RDV/DCT/Active STAR IZOL' },
    { id: '10', type: 'Short Haul', departure: 'IZOL', arrival: 'IPPH', routing: 'IZOL RDV/DCT/Active SID MORRD DOGGO RDV/DCT/Active STAR IPPH' },
    { id: '11', type: 'Medium Haul', departure: 'IRFD', arrival: 'ILAR', routing: 'IRFD RDV/DCT/Active SID LAZER IHEN RDV/DCT/Active STAR ILAR' },
    { id: '12', type: 'Medium Haul', departure: 'ILAR', arrival: 'IRFD', routing: 'ILAR RDV/DCT/Active SID IHEN LAZER RDV/DCT/Active STAR IRFD' },
    { id: '13', type: 'Medium Haul', departure: 'IPPH', arrival: 'ILAR', routing: 'IPPH RDV/DCT/Active SID SISTA JACKI RDV/DCT/Active STAR ILAR' },
    { id: '14', type: 'Medium Haul', departure: 'ILAR', arrival: 'IPPH', routing: 'ILAR RDV/DCT/Active SID JACKI SISTA RDV/DCT/Active STAR IPPH' },
    { id: '15', type: 'Medium Haul', departure: 'IPPH', arrival: 'IKFL', routing: 'IPPH RDV/DCT/Active SID WELLS SQUID RDV/DCT/Active STAR IKFL' },
    { id: '16', type: 'Medium Haul', departure: 'IKFL', arrival: 'IPPH', routing: 'IKFL RDV/DCT/Active SID SQUID WELLS RDV/DCT/Active STAR IPPH' },
    { id: '17', type: 'Medium Haul', departure: 'IRFD', arrival: 'IPAP', routing: 'IRFD RDV/DCT/Active SID PEPUL IBAR RDV/DCT/Active STAR IPAP' },
    { id: '18', type: 'Medium Haul', departure: 'IPAP', arrival: 'IRFD', routing: 'IPAP RDV/DCT/Active SID IBAR PEPUL RDV/DCT/Active STAR IRFD' },
    { id: '19', type: 'Long Haul', departure: 'IRFD', arrival: 'ITKO', routing: 'IRFD RDV/DCT/Active SID TUDEP ASTRO RDV/DCT/Active STAR ITKO' },
    { id: '20', type: 'Long Haul', departure: 'ITKO', arrival: 'IRFD', routing: 'ITKO RDV/DCT/Active SID ASTRO TUDEP RDV/DCT/Active STAR IRFD' },
    { id: '21', type: 'Long Haul', departure: 'IRFD', arrival: 'IKFL', routing: 'IRFD RDV/DCT/Active SID BLANK FROOT RDV/DCT/Active STAR IKFL' },
    { id: '22', type: 'Long Haul', departure: 'IKFL', arrival: 'IRFD', routing: 'IKFL RDV/DCT/Active SID FROOT BLANK RDV/DCT/Active STAR IRFD' },
    { id: '23', type: 'Long Haul', departure: 'IPPH', arrival: 'IPAP', routing: 'IPPH RDV/DCT/Active SID DUNKS IPAP RDV/DCT/Active STAR IPAP' },
    { id: '24', type: 'Long Haul', departure: 'IPAP', arrival: 'IPPH', routing: 'IPAP RDV/DCT/Active SID IPAP DUNKS RDV/DCT/Active STAR IPPH' },
    { id: '25', type: 'Cargo', departure: 'IRFD', arrival: 'IKFL', routing: 'IRFD RDV/DCT/Active SID BLANK FROOT RDV/DCT/Active STAR IKFL' },
    { id: '26', type: 'Cargo', departure: 'IKFL', arrival: 'IRFD', routing: 'IKFL RDV/DCT/Active SID FROOT BLANK RDV/DCT/Active STAR IRFD' },
    { id: '27', type: 'Cargo', departure: 'IRFD', arrival: 'ITKO', routing: 'IRFD RDV/DCT/Active SID TUDEP ASTRO RDV/DCT/Active STAR ITKO' },
    { id: '28', type: 'Cargo', departure: 'ITKO', arrival: 'IRFD', routing: 'ITKO RDV/DCT/Active SID ASTRO TUDEP RDV/DCT/Active STAR IRFD' },
    { id: '29', type: 'Cargo', departure: 'IPPH', arrival: 'ITKO', routing: 'IPPH RDV/DCT/Active SID LETSE SHIBA RDV/DCT/Active STAR ITKO' },
    { id: '30', type: 'Cargo', departure: 'ITKO', arrival: 'IPPH', routing: 'ITKO RDV/DCT/Active SID SHIBA LETSE RDV/DCT/Active STAR IPPH' },
    { id: '31', type: 'Cargo', departure: 'IRFD', arrival: 'IZOL', routing: 'IRFD RDV/DCT/Active SID OCEEN TRESIN RDV/DCT/Active STAR IZOL' },
    { id: '32', type: 'Cargo', departure: 'IZOL', arrival: 'IRFD', routing: 'IZOL RDV/DCT/Active SID TRESIN OCEEN RDV/DCT/Active STAR IRFD' },
    { id: '33', type: 'Cargo', departure: 'IPPH', arrival: 'IZOL', routing: 'IPPH RDV/DCT/Active SID DOGGO MORRD RDV/DCT/Active STAR IZOL' },
    { id: '34', type: 'Cargo', departure: 'IZOL', arrival: 'IPPH', routing: 'IZOL RDV/DCT/Active SID MORRD DOGGO RDV/DCT/Active STAR IPPH' },
    { id: '35', type: 'Cargo', departure: 'IRFD', arrival: 'ILAR', routing: 'IRFD RDV/DCT/Active SID LAZER IHEN RDV/DCT/Active STAR ILAR' },
    { id: '36', type: 'Cargo', departure: 'ILAR', arrival: 'IRFD', routing: 'ILAR RDV/DCT/Active SID IHEN LAZER RDV/DCT/Active STAR IRFD' },
    { id: '37', type: 'Cargo', departure: 'IPPH', arrival: 'ILAR', routing: 'IPPH RDV/DCT/Active SID SISTA JACKI RDV/DCT/Active STAR ILAR' },
    { id: '38', type: 'Cargo', departure: 'ILAR', arrival: 'IPPH', routing: 'ILAR RDV/DCT/Active SID JACKI SISTA RDV/DCT/Active STAR IPPH' },
];

module.exports = { ROUTES };
