const ROUTES = [
    { id: '1', type: 'Domestic', departure: 'EDDF', arrival: 'EDDM', routing: 'EDDF RDV/DCT/Active SID RES INDEX GAVIN SILVA STRAX RDV/DCT/Active STAR EDDM', time: '01:00', distance: 160 },
    { id: '2', type: 'Domestic', departure: 'EDDM', arrival: 'EDDF', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA GAVIN INDEX RES RDV/DCT/Active STAR EDDF', time: '01:00', distance: 160 },
    { id: '3', type: 'Domestic', departure: 'EDDF', arrival: 'EDDW', routing: 'EDDF RDV/DCT/Active SID MLR RDV/DCT/Active STAR EDDW', time: '01:00', distance: 180 },
    { id: '4', type: 'Domestic', departure: 'EDDW', arrival: 'EDDF', routing: 'EDDW RDV/DCT/Active SID MLR RDV/DCT/Active STAR EDDF', time: '01:00', distance: 180 },
    { id: '5', type: 'Domestic', departure: 'EDDM', arrival: 'EDDW', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA GAVIN INDEX RES RDV/DCT/Active STAR EDDW', time: '01:00', distance: 250 },
    { id: '6', type: 'Domestic', departure: 'EDDW', arrival: 'EDDM', routing: 'EDDW RDV/DCT/Active SID RES INDEX GAVIN SILVA STRAX RDV/DCT/Active STAR EDDM', time: '01:00', distance: 250 },
    { id: '7', type: 'Short Haul', departure: 'EDDF', arrival: 'LFPG', routing: 'EDDF RDV/DCT/Active SID WAREZ SEEKS RDV/DCT/Active STAR LFPG', time: '01:15', distance: 260 },
    { id: '8', type: 'Short Haul', departure: 'LFPG', arrival: 'EDDF', routing: 'LFPG RDV/DCT/Active SID SEEKS WAREZ RDV/DCT/Active STAR EDDF', time: '01:15', distance: 260 },
    { id: '9', type: 'Short Haul', departure: 'EDDM', arrival: 'LIRF', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA VOX CAMEL TRE ISCM RDV/DCT/Active STAR LIRF', time: '01:30', distance: 380 },
    { id: '10', type: 'Short Haul', departure: 'LIRF', arrival: 'EDDM', routing: 'LIRF RDV/DCT/Active SID ISCM TRE CAMEL VOX SILVA STRAX RDV/DCT/Active STAR EDDM', time: '01:30', distance: 380 },
    { id: '11', type: 'Medium Haul', departure: 'EDDF', arrival: 'LGAV', routing: 'EDDF RDV/DCT/Active SID MLR STOOD JAMSI LAZER LCK RDV/DCT/Active STAR LGAV', time: '02:45', distance: 1000 },
    { id: '12', type: 'Medium Haul', departure: 'LGAV', arrival: 'EDDF', routing: 'LGAV RDV/DCT/Active SID LCK LAZER JAMSI STOOD MLR RDV/DCT/Active STAR EDDF', time: '02:45', distance: 1000 },
    { id: '13', type: 'Medium Haul', departure: 'EDDM', arrival: 'LGAV', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA DEL ISKP RENTS GRASS RDV/DCT/Active STAR LGAV', time: '02:15', distance: 800 },
    { id: '14', type: 'Medium Haul', departure: 'LGAV', arrival: 'EDDM', routing: 'LGAV RDV/DCT/Active SID GRASS RENTS ISKP DEL SILVA STRAX RDV/DCT/Active STAR EDDM', time: '02:15', distance: 800 },
    { id: '15', type: 'Medium Haul', departure: 'EDDM', arrival: 'EGLL', routing: 'EDDM RDV/DCT/Active SID SHV RDV/DCT/Active STAR EGLL', time: '01:45', distance: 500 },
    { id: '16', type: 'Medium Haul', departure: 'EGLL', arrival: 'EDDM', routing: 'EGLL RDV/DCT/Active SID SHV RDV/DCT/Active STAR EDDM', time: '01:45', distance: 500 },
    { id: '17', type: 'Medium Haul', departure: 'EDDF', arrival: 'LEPA', routing: 'EDDF RDV/DCT/Active SID MLR STOOD JAMSI LAZER LCK IBAR RDV/DCT/Active STAR LEPA', time: '02:00', distance: 680 },
    { id: '18', type: 'Medium Haul', departure: 'LEPA', arrival: 'EDDF', routing: 'LEPA RDV/DCT/Active SID IBAR LCK LAZER JAMSI STOOD MLR RDV/DCT/Active STAR EDDF', time: '02:00', distance: 680 },
    { id: '19', type: 'Long Haul', departure: 'EDDF', arrival: 'RJTT', routing: 'EDDF RDV/DCT/Active SID RES PROBE RENDR SOTAF ONDER KNIFE HONDA RDV/DCT/Active STAR RJTT', time: '11:15', distance: 5100 },
    { id: '20', type: 'Long Haul', departure: 'RJTT', arrival: 'EDDF', routing: 'RJTT RDV/DCT/Active SID HONDA KNIFE ONDER SOTAF RENDR PROBE RES RDV/DCT/Active STAR EDDF', time: '11:15', distance: 5100 },
    { id: '21', type: 'Long Haul', departure: 'EDDF', arrival: 'EGLL', routing: 'EDDF RDV/DCT/Active SID RES INDEX GAVIN SILVA STRAX RDV/DCT/Active STAR EGLL', time: '01:30', distance: 350 },
    { id: '22', type: 'Long Haul', departure: 'EGLL', arrival: 'EDDF', routing: 'EGLL RDV/DCT/Active SID STRAX SILVA GAVIN INDEX RES RDV/DCT/Active STAR EDDF', time: '01:30', distance: 350 },
    { id: '23', type: 'Long Haul', departure: 'EDDM', arrival: 'LEPA', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA DEL ISKP RENTS GRASS JACKI RDV/DCT/Active STAR LEPA', time: '02:00', distance: 630 },
    { id: '24', type: 'Long Haul', departure: 'LEPA', arrival: 'EDDM', routing: 'LEPA RDV/DCT/Active SID JACKI GRASS RENTS ISKP DEL SILVA STRAX RDV/DCT/Active STAR EDDM', time: '02:00', distance: 630 },
    { id: '25', type: 'Cargo', departure: 'EDDF', arrival: 'EGLL', routing: 'EDDF RDV/DCT/Active SID RES INDEX GAVIN SILVA STRAX RDV/DCT/Active STAR EGLL', time: '01:30', distance: 350 },
    { id: '26', type: 'Cargo', departure: 'EGLL', arrival: 'EDDF', routing: 'EGLL RDV/DCT/Active SID STRAX SILVA GAVIN INDEX RES RDV/DCT/Active STAR EDDF', time: '01:30', distance: 350 },
    { id: '27', type: 'Cargo', departure: 'EDDF', arrival: 'RJTT', routing: 'EDDF RDV/DCT/Active SID RES PROBE RENDR SOTAF ONDER KNIFE HONDA RDV/DCT/Active STAR RJTT', time: '11:15', distance: 5100 },
    { id: '28', type: 'Cargo', departure: 'RJTT', arrival: 'EDDF', routing: 'RJTT RDV/DCT/Active SID HONDA KNIFE ONDER SOTAF RENDR PROBE RES RDV/DCT/Active STAR EDDF', time: '11:15', distance: 5100 },
    { id: '29', type: 'Cargo', departure: 'EDDM', arrival: 'RJTT', routing: 'EDDM RDV/DCT/Active SID STRAX ROM SOTAF ONDER KNIFE HONDA RDV/DCT/Active STAR RJTT', time: '11:10', distance: 5050 },
    { id: '30', type: 'Cargo', departure: 'RJTT', arrival: 'EDDM', routing: 'RJTT RDV/DCT/Active SID HONDA KNIFE ONDER SOTAF ROM STRAX RDV/DCT/Active STAR EDDM', time: '11:10', distance: 5050 },
    { id: '31', type: 'Cargo', departure: 'EDDF', arrival: 'LIRF', routing: 'EDDF RDV/DCT/Active SID MLR STOOD JAMSI ANYMS ISKP DEL IZCG RDV/DCT/Active STAR LIRF', time: '01:45', distance: 520 },
    { id: '32', type: 'Cargo', departure: 'LIRF', arrival: 'EDDF', routing: 'LIRF RDV/DCT/Active SID IZCG DEL ISKP ANYMS JAMSI STOOD MLR RDV/DCT/Active STAR EDDF', time: '01:45', distance: 520 },
    { id: '33', type: 'Cargo', departure: 'EDDM', arrival: 'LIRF', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA VOX CAMEL TRE ISCM RDV/DCT/Active STAR LIRF', time: '01:30', distance: 380 },
    { id: '34', type: 'Cargo', departure: 'LIRF', arrival: 'EDDM', routing: 'LIRF RDV/DCT/Active SID ISCM TRE CAMEL VOX SILVA STRAX RDV/DCT/Active STAR EDDM', time: '01:30', distance: 380 },
    { id: '35', type: 'Cargo', departure: 'EDDF', arrival: 'LGAV', routing: 'EDDF RDV/DCT/Active SID MLR STOOD JAMSI LAZER LCK RDV/DCT/Active STAR LGAV', time: '02:45', distance: 1000 },
    { id: '36', type: 'Cargo', departure: 'LGAV', arrival: 'EDDF', routing: 'LGAV RDV/DCT/Active SID LCK LAZER JAMSI STOOD MLR RDV/DCT/Active STAR EDDF', time: '02:45', distance: 1000 },
    { id: '37', type: 'Cargo', departure: 'EDDM', arrival: 'LGAV', routing: 'EDDM RDV/DCT/Active SID STRAX SILVA DEL ISKP RENTS GRASS RDV/DCT/Active STAR LGAV', time: '02:15', distance: 800 },
    { id: '38', type: 'Cargo', departure: 'LGAV', arrival: 'EDDM', routing: 'LGAV RDV/DCT/Active SID GRASS RENTS ISKP DEL SILVA STRAX RDV/DCT/Active STAR EDDM', time: '02:15', distance: 800 },
];

module.exports = { ROUTES };
